from PyQt6.QtGui import QColor

THEMES = {
    "Lumen Dark": {
        "type": "dark",
        "colors": {
            "bg": QColor("#1e1e2e"),
            "fg": QColor("#cdd6f4"),
            "title_bg": QColor("#313244"),
            "title_bg_darker": QColor("#29293b"),
            "title_fg": QColor("#cdd6f4"),
            "title_border": QColor("#45475a"),
            "keyword": QColor("#f5c2e7"),
            "type": QColor("#cba6f7"),
            "comment": QColor("#6c7086"),
            "string": QColor("#a6e3a1"),
            "number": QColor("#fab387"),
            "operator": QColor("#6c7086"),
            "function": QColor("#89b4fa"),
            "modifier": QColor("#b4befe"),
            "directive": QColor("#f5e0dc"),
            "literal": QColor("#f9e2af"),
            "namespace": QColor("#94e2d5"),
            "special": QColor("#f2b5b5"),
            "object": QColor("#f2cdcd"),
            "caret": QColor("#ffffff"),
            "caret_line": QColor("#313244"),
            "margin_bg": QColor("#181825"),
            "margin_fg": QColor("#6c7086"),
            "selection_bg": QColor("#585b70"),
            "selection_fg": QColor("#ffffff"),
            "brace_bg": QColor("#f5c2e755"),
            "brace_fg": QColor("#f5c2e7"),
            "error": QColor("#f35815"),
            "warning": QColor("#ffc413"),
            "autosave_on": QColor("#a6e3a1"),
            "autosave_off": QColor("#f38ba8"),
            "status_bg": QColor("#181825"),
            "status_border": QColor("#313244"),
        }
    },
    
    "Lumen Classic": {
        "type": "light",
        "colors": {
            "bg": QColor("#eff1f5"),
            "fg": QColor("#4c4f69"),
            "title_bg": QColor("#dce0e8"),
            "title_bg_darker": QColor("#c9cdd8"),
            "title_fg": QColor("#4c4f69"),
            "title_border": QColor("#bcc0cc"),
            "keyword": QColor("#859900"),
            "type": QColor("#b58900"),
            "comment": QColor("#93a1a1"),
            "string": QColor("#2aa198"),
            "number": QColor("#d33682"),
            "operator": QColor("#657b83"),
            "function": QColor("#155e93"),
            "modifier": QColor("#6c71c4"),
            "directive": QColor("#cb4b16"),
            "literal": QColor("#dc322f"),
            "namespace": QColor("#268bd2"),
            "special": QColor("#d33682"),
            "object": QColor("#2a9781"),
            "caret": QColor("#1e1e2e"),
            "caret_line": QColor("#e6e9ef"),
            "margin_bg": QColor("#dce0e8"),
            "margin_fg": QColor("#6c6f85"),
            "selection_bg": QColor("#acb0be"),
            "selection_fg": QColor("#1e1e2e"),
            "brace_bg": QColor("#8839ef55"),
            "brace_fg": QColor("#8839ef"),
            "error": QColor("#f35815"),
            "warning": QColor("#ffc413"),
            "autosave_on": QColor("#a6e3a1"),
            "autosave_off": QColor("#f38ba8"),
            "status_bg": QColor("#2d2d3a"),
            "status_border": QColor("#4c4f69"),
        }
    },
    
    "Solarized Dark": {
        "type": "dark",
        "colors": {
            "bg": QColor("#002b36"),
            "fg": QColor("#839496"),
            "title_bg": QColor("#073642"),
            "title_bg_darker": QColor("#032f39"),
            "title_fg": QColor("#fdf6e3"),
            "title_border": QColor("#586e75"),
            "keyword": QColor("#859900"),
            "type": QColor("#b58900"),
            "comment": QColor("#586e75"),
            "string": QColor("#2aa198"),
            "number": QColor("#d33682"),
            "operator": QColor("#657b83"),
            "function": QColor("#268bd2"),
            "modifier": QColor("#6c71c4"),
            "directive": QColor("#cb4b16"),
            "literal": QColor("#dc322f"),
            "namespace": QColor("#268bd2"),
            "special": QColor("#d33682"),
            "object": QColor("#b58900"),
            "caret": QColor("#ffffff"),
            "caret_line": QColor("#073642"),
            "margin_bg": QColor("#073642"),
            "margin_fg": QColor("#586e75"),
            "selection_bg": QColor("#586e75"),
            "selection_fg": QColor("#fdf6e3"),
            "brace_bg": QColor("#85990055"),
            "brace_fg": QColor("#859900"),
            "error": QColor("#dc322f"),
            "warning": QColor("#b58900"),
            "autosave_on": QColor("#2aa198"),
            "autosave_off": QColor("#dc322f"),
            "status_bg": QColor("#073642"),
            "status_border": QColor("#586e75"),
        }
    },
    
    "Solarized Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#fdf6e3"),
            "fg": QColor("#657b83"),
            "title_bg": QColor("#eee8d5"),
            "title_bg_darker": QColor("#ddd6c3"),
            "title_fg": QColor("#586e75"),
            "title_border": QColor("#93a1a1"),
            "keyword": QColor("#859900"),
            "type": QColor("#b58900"),
            "comment": QColor("#93a1a1"),
            "string": QColor("#2aa198"),
            "number": QColor("#d33682"),
            "operator": QColor("#657b83"),
            "function": QColor("#268bd2"),
            "modifier": QColor("#6c71c4"),
            "directive": QColor("#cb4b16"),
            "literal": QColor("#dc322f"),
            "namespace": QColor("#268bd2"),
            "special": QColor("#d33682"),
            "object": QColor("#b58900"),
            "caret": QColor("#002b36"),
            "caret_line": QColor("#eee8d5"),
            "margin_bg": QColor("#eee8d5"),
            "margin_fg": QColor("#93a1a1"),
            "selection_bg": QColor("#93a1a1"),
            "selection_fg": QColor("#002b36"),
            "brace_bg": QColor("#85990055"),
            "brace_fg": QColor("#859900"),
            "error": QColor("#dc322f"),
            "warning": QColor("#b58900"),
            "autosave_on": QColor("#2aa198"),
            "autosave_off": QColor("#dc322f"),
            "status_bg": QColor("#073642"),
            "status_border": QColor("#586e75"),
        }
    },
    
    "Nord": {
        "type": "dark",
        "colors": {
            "bg": QColor("#2e3440"),
            "fg": QColor("#d8dee9"),
            "title_bg": QColor("#3b4252"),
            "title_bg_darker": QColor("#2f3644"),
            "title_fg": QColor("#eceff4"),
            "title_border": QColor("#4c566a"),
            "keyword": QColor("#81a1c1"),
            "type": QColor("#938eb4"),
            "comment": QColor("#4c566a"),
            "string": QColor("#a3be8c"),
            "number": QColor("#b48ead"),
            "operator": QColor("#81a1c1"),
            "function": QColor("#88c0d0"),
            "modifier": QColor("#81a1c1"),
            "directive": QColor("#d08770"),
            "literal": QColor("#d8dee9"),
            "namespace": QColor("#8fbcbb"),
            "special": QColor("#d08770"),
            "object": QColor("#8fbcbb"),
            "caret": QColor("#eceff4"),
            "caret_line": QColor("#3b4252"),
            "margin_bg": QColor("#3b4252"),
            "margin_fg": QColor("#4c566a"),
            "selection_bg": QColor("#4c566a"),
            "selection_fg": QColor("#eceff4"),
            "brace_bg": QColor("#81a1c155"),
            "brace_fg": QColor("#81a1c1"),
            "error": QColor("#bf616a"),
            "warning": QColor("#ebcb8b"),
            "autosave_on": QColor("#a3be8c"),
            "autosave_off": QColor("#bf616a"),
            "status_bg": QColor("#3b4252"),
            "status_border": QColor("#4c566a"),
        }
    },
    
    "Nord Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#e5e9f0"),
            "fg": QColor("#2e3440"),
            "title_bg": QColor("#d8dee9"),
            "title_bg_darker": QColor("#d8dee9"),
            "title_fg": QColor("#2e3440"),
            "title_border": QColor("#81a1c1"),
            "keyword": QColor("#5e81ac"),
            "type": QColor("#938eb4"),
            "comment": QColor("#81a1c1"),
            "string": QColor("#a3be8c"),
            "number": QColor("#b48ead"),
            "operator": QColor("#5e81ac"),
            "function": QColor("#88c0d0"),
            "modifier": QColor("#5e81ac"),
            "directive": QColor("#d08770"),
            "literal": QColor("#2e3440"),
            "namespace": QColor("#8fbcbb"),
            "special": QColor("#d08770"),
            "object": QColor("#8fbcbb"),
            "caret": QColor("#2e3440"),
            "caret_line": QColor("#d8dee9"),
            "margin_bg": QColor("#d8dee9"),
            "margin_fg": QColor("#81a1c1"),
            "selection_bg": QColor("#81a1c1"),
            "selection_fg": QColor("#2e3440"),
            "brace_bg": QColor("#5e81ac55"),
            "brace_fg": QColor("#5e81ac"),
            "error": QColor("#bf616a"),
            "warning": QColor("#ebcb8b"),
            "autosave_on": QColor("#a3be8c"),
            "autosave_off": QColor("#bf616a"),
            "status_bg": QColor("#3b4252"),
            "status_border": QColor("#4c566a"),
        }
    },
    
    "Visual Studio Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#ffffff"),
            "fg": QColor("#000000"),
            "title_bg": QColor("#f0f0f0"),
            "title_bg_darker": QColor("#dddddd"),
            "title_fg": QColor("#000000"),
            "title_border": QColor("#cccccc"),
            "keyword": QColor("#0000ff"),
            "type": QColor("#2b91af"),
            "comment": QColor("#008000"),
            "string": QColor("#a31515"),
            "number": QColor("#09885a"),
            "operator": QColor("#000000"),
            "function": QColor("#795e26"),
            "modifier": QColor("#0000ff"),
            "directive": QColor("#008000"),
            "literal": QColor("#a31515"),
            "namespace": QColor("#267f99"),
            "special": QColor("#ff0000"),
            "object": QColor("#2b91af"),
            "caret": QColor("#000000"),
            "caret_line": QColor("#f0f0f0"),
            "margin_bg": QColor("#f0f0f0"),
            "margin_fg": QColor("#606060"),
            "selection_bg": QColor("#fff8d3"),
            "selection_fg": QColor("#000000"),
            "brace_bg": QColor("#0078d755"),
            "brace_fg": QColor("#0078d7"),
            "error": QColor("#ff0000"),
            "warning": QColor("#ff8c00"),
            "autosave_on": QColor("#107c10"),
            "autosave_off": QColor("#d73a49"),
            "status_bg": QColor("#2d2d2d"),
            "status_border": QColor("#cccccc"),
        }
    },
    
    "Ayu Dark": {
    "type": "dark",
    "colors": {
        "bg": QColor("#0a0e14"),
        "fg": QColor("#b3b1ad"),
        "title_bg": QColor("#1a1f29"),
        "title_bg_darker": QColor("#0f141e"),
        "title_fg": QColor("#e6e1cf"),
        "title_border": QColor("#4c6a83"),  # изменённый цвет для яркого наведения
        "keyword": QColor("#ff8f40"),
        "type": QColor("#39bae6"),
        "comment": QColor("#626a73"),
        "string": QColor("#c2d94c"),
        "number": QColor("#d2a6ff"),
        "operator": QColor("#f29668"),
        "function": QColor("#ffb454"),
        "modifier": QColor("#4086ff"),
        "directive": QColor("#e6b450"),
        "literal": QColor("#a37acc"),
        "namespace": QColor("#39bae6"),
        "special": QColor("#f07178"),
        "object": QColor("#95e6cb"),
        "caret": QColor("#e6e1cf"),
        "caret_line": QColor("#1a1f29"),
        "margin_bg": QColor("#0d1017"),
        "margin_fg": QColor("#3e4b59"),
        "selection_bg": QColor("#273747"),
        "selection_fg": QColor("#e6e1cf"),
        "brace_bg": QColor("#ff8f4055"),
        "brace_fg": QColor("#ff8f40"),
        "error": QColor("#f07178"),
        "warning": QColor("#ffb454"),
        "autosave_on": QColor("#c2d94c"),
        "autosave_off": QColor("#f07178"),
        "status_bg": QColor("#0d1017"),
        "status_border": QColor("#273747"),
    }
},
    
    "Ayu Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#fafafa"),
            "fg": QColor("#5c6166"),
            "title_bg": QColor("#e9e9e9"),
            "title_bg_darker": QColor("#d8d8d8"),
            "title_fg": QColor("#5c6166"),
            "title_border": QColor("#abb0b6"),
            "keyword": QColor("#fa8d3e"),
            "type": QColor("#399ee6"),
            "comment": QColor("#abb0b6"),
            "string": QColor("#86b300"),
            "number": QColor("#a37acc"),
            "operator": QColor("#ed9366"),
            "function": QColor("#f2ae49"),
            "modifier": QColor("#6a3efa"),
            "directive": QColor("#f2ae49"),
            "literal": QColor("#a37acc"),
            "namespace": QColor("#399ee6"),
            "special": QColor("#f07171"),
            "object": QColor("#4cbf99"),
            "caret": QColor("#5c6166"),
            "caret_line": QColor("#f0f0f0"),
            "margin_bg": QColor("#e9e9e9"),
            "margin_fg": QColor("#abb0b6"),
            "selection_bg": QColor("#d4d4d4"),
            "selection_fg": QColor("#5c6166"),
            "brace_bg": QColor("#fa8d3e55"),
            "brace_fg": QColor("#fa8d3e"),
            "error": QColor("#f07171"),
            "warning": QColor("#f2ae49"),
            "autosave_on": QColor("#86b300"),
            "autosave_off": QColor("#f07171"),
            "status_bg": QColor("#2d3c4d"),
            "status_border": QColor("#abb0b6"),
        }
    },
    
    "Everforest Dark": {
        "type": "dark",
        "colors": {
            "bg": QColor("#2d3c4d"),
            "fg": QColor("#d3c6aa"),
            "title_bg": QColor("#3a4a5a"),
            "title_bg_darker": QColor("#2f3f4f"),
            "title_fg": QColor("#d3c6aa"),
            "title_border": QColor("#4a5a6a"),
            "keyword": QColor("#e6986c"),
            "type": QColor("#7fbbb3"),
            "comment": QColor("#859289"),
            "string": QColor("#a7c080"),
            "number": QColor("#e67e80"),
            "operator": QColor("#e6986c"),
            "function": QColor("#dbbc7f"),
            "modifier": QColor("#e6986c"),
            "directive": QColor("#e67e80"),
            "literal": QColor("#e67e80"),
            "namespace": QColor("#7fbbb3"),
            "special": QColor("#e67e80"),
            "object": QColor("#a7c080"),
            "caret": QColor("#d3c6aa"),
            "caret_line": QColor("#3a4a5a"),
            "margin_bg": QColor("#26323f"),
            "margin_fg": QColor("#859289"),
            "selection_bg": QColor("#4a5a6a"),
            "selection_fg": QColor("#d3c6aa"),
            "brace_bg": QColor("#e6986c55"),
            "brace_fg": QColor("#e6986c"),
            "error": QColor("#e67e80"),
            "warning": QColor("#e6986c"),
            "autosave_on": QColor("#a7c080"),
            "autosave_off": QColor("#e67e80"),
            "status_bg": QColor("#26323f"),
            "status_border": QColor("#4a5a6a"),
        }
    },
    
    "Everforest Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#fef6e4"),
            "fg": QColor("#5c6a72"),
            "title_bg": QColor("#f0e8d8"),
            "title_bg_darker": QColor("#e0d8c8"),
            "title_fg": QColor("#5c6a72"),
            "title_border": QColor("#d0d8d0"),
            "keyword": QColor("#f57b5c"),
            "type": QColor("#4f9e9e"),
            "comment": QColor("#939f91"),
            "string": QColor("#8da101"),
            "number": QColor("#e65e5e"),
            "operator": QColor("#f57b5c"),
            "function": QColor("#dfb256"),
            "modifier": QColor("#f57b5c"),
            "directive": QColor("#e65e5e"),
            "literal": QColor("#e65e5e"),
            "namespace": QColor("#4f9e9e"),
            "special": QColor("#e65e5e"),
            "object": QColor("#8da101"),
            "caret": QColor("#5c6a72"),
            "caret_line": QColor("#f0e8d8"),
            "margin_bg": QColor("#e8e0d0"),
            "margin_fg": QColor("#939f91"),
            "selection_bg": QColor("#d0d8d0"),
            "selection_fg": QColor("#5c6a72"),
            "brace_bg": QColor("#f57b5c55"),
            "brace_fg": QColor("#f57b5c"),
            "error": QColor("#e65e5e"),
            "warning": QColor("#f57b5c"),
            "autosave_on": QColor("#8da101"),
            "autosave_off": QColor("#e65e5e"),
            "status_bg": QColor("#3a4a5a"),
            "status_border": QColor("#939f91"),
        }
    },
    
    "Rosé Pine": {
        "type": "dark",
        "colors": {
            "bg": QColor("#191724"),
            "fg": QColor("#e0def4"),
            "title_bg": QColor("#26233a"),
            "title_bg_darker": QColor("#1c192d"),
            "title_fg": QColor("#e0def4"),
            "title_border": QColor("#403d52"),
            "keyword": QColor("#ebbcba"),
            "type": QColor("#9ccfd8"),
            "comment": QColor("#6e6a86"),
            "string": QColor("#f6c177"),
            "number": QColor("#c4a7e7"),
            "operator": QColor("#e0def4"),
            "function": QColor("#ebbcba"),
            "modifier": QColor("#c4a7e7"),
            "directive": QColor("#eb6f92"),
            "literal": QColor("#f6c177"),
            "namespace": QColor("#9ccfd8"),
            "special": QColor("#eb6f92"),
            "object": QColor("#c4a7e7"),
            "caret": QColor("#e0def4"),
            "caret_line": QColor("#26233a"),
            "margin_bg": QColor("#1f1d2e"),
            "margin_fg": QColor("#6e6a86"),
            "selection_bg": QColor("#403d52"),
            "selection_fg": QColor("#e0def4"),
            "brace_bg": QColor("#ebbcba55"),
            "brace_fg": QColor("#ebbcba"),
            "error": QColor("#eb6f92"),
            "warning": QColor("#f6c177"),
            "autosave_on": QColor("#9ccfd8"),
            "autosave_off": QColor("#eb6f92"),
            "status_bg": QColor("#1f1d2e"),
            "status_border": QColor("#403d52"),
        }
    },
}