from PyQt6.QtGui import QColor

THEMES = {
    "Pure Light": {
    "type": "light",
    "colors": {
        "bg": QColor("#ffffff"),
        "fg": QColor("#202020"),
        "title_bg": QColor("#f5f5f5"),
        "title_bg_darker": QColor("#e8e8e8"),
        "title_fg": QColor("#202020"),
        "title_border": QColor("#d0d0d0"),
        "keyword": QColor("#0000cc"),
        "type": QColor("#007a7a"),
        "comment": QColor("#6a6a6a"),
        "string": QColor("#a31515"),
        "number": QColor("#09885a"),
        "operator": QColor("#202020"),
        "function": QColor("#795e26"),
        "modifier": QColor("#6c71c4"),
        "directive": QColor("#ca4b16"),
        "literal": QColor("#b80000"),
        "namespace": QColor("#267f99"),
        "special": QColor("#d33682"),
        "object": QColor("#2a9781"),
        "caret": QColor("#000000"),
        "caret_line": QColor("#f0f0f0"),
        "margin_bg": QColor("#f8f8f8"),
        "margin_fg": QColor("#808080"),
        "selection_bg": QColor("#cce0ff"),
        "selection_fg": QColor("#000000"),
        "brace_bg": QColor("#0078d755"),
        "brace_fg": QColor("#0078d7"),
        "error": QColor("#d73a49"),
        "warning": QColor("#e36209"),
        "echo": QColor("#a0a0a0"),
        "autosave_on": QColor("#28a745"),
        "autosave_off": QColor("#d73a49"),
        "status_bg": QColor("#2d2d30"),
        "status_border": QColor("#d0d0d0"),
    }
},
    "Lumen Dark": {
        "type": "dark",
        "colors": {
            "bg": QColor("#1e1e2e"),
            "fg": QColor("#cdd6f4"),
            "title_bg": QColor("#313244"),
            "title_bg_darker": QColor("#29293b"),
            "title_fg": QColor("#cdd6f4"),
            "title_border": QColor("#45475a"),
            "keyword": QColor("#f5c2e7"),
            "type": QColor("#cba6f7"),
            "comment": QColor("#6c7086"),
            "string": QColor("#a6e3a1"),
            "number": QColor("#fab387"),
            "operator": QColor("#6c7086"),
            "function": QColor("#89b4fa"),
            "modifier": QColor("#b4befe"),
            "directive": QColor("#f5e0dc"),
            "literal": QColor("#f9e2af"),
            "namespace": QColor("#94e2d5"),
            "special": QColor("#f2b5b5"),
            "object": QColor("#f2cdcd"),
            "caret": QColor("#ffffff"),
            "caret_line": QColor("#313244"),
            "margin_bg": QColor("#181825"),
            "margin_fg": QColor("#6c7086"),
            "selection_bg": QColor("#585b70"),
            "selection_fg": QColor("#ffffff"),
            "brace_bg": QColor("#f5c2e755"),
            "brace_fg": QColor("#f5c2e7"),
            "error": QColor("#f35815"),
            "warning": QColor("#ffc413"),
            "echo": QColor("#a6adc8"),  # светлее фона, но темнее основного текста
            "autosave_on": QColor("#a6e3a1"),
            "autosave_off": QColor("#f38ba8"),
            "status_bg": QColor("#181825"),
            "status_border": QColor("#313244"),
        }
    },
    
    "Lumen Classic": {
        "type": "light",
        "colors": {
            "bg": QColor("#eff1f5"),
            "fg": QColor("#4c4f69"),
            "title_bg": QColor("#dce0e8"),
            "title_bg_darker": QColor("#c9cdd8"),
            "title_fg": QColor("#4c4f69"),
            "title_border": QColor("#bcc0cc"),
            "keyword": QColor("#859900"),
            "type": QColor("#b58900"),
            "comment": QColor("#93a1a1"),
            "string": QColor("#2aa198"),
            "number": QColor("#d33682"),
            "operator": QColor("#657b83"),
            "function": QColor("#155e93"),
            "modifier": QColor("#6c71c4"),
            "directive": QColor("#cb4b16"),
            "literal": QColor("#dc322f"),
            "namespace": QColor("#268bd2"),
            "special": QColor("#d33682"),
            "object": QColor("#2a9781"),
            "caret": QColor("#1e1e2e"),
            "caret_line": QColor("#e6e9ef"),
            "margin_bg": QColor("#dce0e8"),
            "margin_fg": QColor("#6c6f85"),
            "selection_bg": QColor("#acb0be"),
            "selection_fg": QColor("#1e1e2e"),
            "brace_bg": QColor("#8839ef55"),
            "brace_fg": QColor("#8839ef"),
            "error": QColor("#f35815"),
            "warning": QColor("#ffc413"),
            "echo": QColor("#9ca0b0"),  # серее основного текста
            "autosave_on": QColor("#a6e3a1"),
            "autosave_off": QColor("#f38ba8"),
            "status_bg": QColor("#2d2d3a"),
            "status_border": QColor("#4c4f69"),
        }
    },

    "Kanagawa Dark": {
    "type": "dark",
    "colors": {
        "bg": QColor("#1f1f28"),
        "fg": QColor("#dcd7ba"),
        "title_bg": QColor("#2a2a37"),
        "title_bg_darker": QColor("#23232e"),
        "title_fg": QColor("#dcd7ba"),
        "title_border": QColor("#363646"),
        "keyword": QColor("#c0a36e"),
        "type": QColor("#7e9cd8"),
        "comment": QColor("#727169"),
        "string": QColor("#98bb6c"),
        "number": QColor("#e46876"),
        "operator": QColor("#727169"),
        "function": QColor("#7fb4ca"),
        "modifier": QColor("#957fb8"),
        "directive": QColor("#ffa066"),
        "literal": QColor("#ffa066"),
        "namespace": QColor("#7e9cd8"),
        "special": QColor("#e46876"),
        "object": QColor("#98bb6c"),
        "caret": QColor("#dcd7ba"),
        "caret_line": QColor("#2a2a37"),
        "margin_bg": QColor("#16161d"),
        "margin_fg": QColor("#727169"),
        "selection_bg": QColor("#2e2e3a"),
        "selection_fg": QColor("#dcd7ba"),
        "brace_bg": QColor("#c0a36e55"),
        "brace_fg": QColor("#c0a36e"),
        "error": QColor("#e46876"),
        "warning": QColor("#ffa066"),
        "echo": QColor("#9e9b93"),
        "autosave_on": QColor("#98bb6c"),
        "autosave_off": QColor("#e46876"),
        "status_bg": QColor("#16161d"),
        "status_border": QColor("#2a2a37"),
    }
},

"Kanagawa Light": {
    "type": "light",
    "colors": {
        "bg": QColor("#f8f4ed"),
        "fg": QColor("#3c3c3c"),
        "title_bg": QColor("#e9e3d9"),
        "title_bg_darker": QColor("#ded8ce"),
        "title_fg": QColor("#3c3c3c"),
        "title_border": QColor("#d0cabc"),
        "keyword": QColor("#ab8b5c"),
        "type": QColor("#5c7eb5"),
        "comment": QColor("#9e9b93"),
        "string": QColor("#6f8f3c"),
        "number": QColor("#c46a6a"),
        "operator": QColor("#9e9b93"),
        "function": QColor("#5f8b9c"),
        "modifier": QColor("#7e6b9c"),
        "directive": QColor("#e48c4c"),
        "literal": QColor("#e48c4c"),
        "namespace": QColor("#5c7eb5"),
        "special": QColor("#d5c254"),
        "object": QColor("#6f8f3c"),
        "caret": QColor("#3c3c3c"),
        "caret_line": QColor("#e9e3d9"),
        "margin_bg": QColor("#ede6dc"),
        "margin_fg": QColor("#9e9b93"),
        "selection_bg": QColor("#d6cfc2"),
        "selection_fg": QColor("#3c3c3c"),
        "brace_bg": QColor("#ab8b5c55"),
        "brace_fg": QColor("#ab8b5c"),
        "error": QColor("#c46a6a"),
        "warning": QColor("#e48c4c"),
        "echo": QColor("#aaa49a"),
        "autosave_on": QColor("#6f8f3c"),
        "autosave_off": QColor("#c46a6a"),
        "status_bg": QColor("#2f2f2f"),
        "status_border": QColor("#b8b2a4"),
    }
},
    
    "Solarized Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#fdf6e3"),
            "fg": QColor("#657b83"),
            "title_bg": QColor("#eee8d5"),
            "title_bg_darker": QColor("#ddd6c3"),
            "title_fg": QColor("#586e75"),
            "title_border": QColor("#93a1a1"),
            "keyword": QColor("#859900"),
            "type": QColor("#b58900"),
            "comment": QColor("#93a1a1"),
            "string": QColor("#2aa198"),
            "number": QColor("#d33682"),
            "operator": QColor("#657b83"),
            "function": QColor("#268bd2"),
            "modifier": QColor("#6c71c4"),
            "directive": QColor("#cb4b16"),
            "literal": QColor("#dc322f"),
            "namespace": QColor("#268bd2"),
            "special": QColor("#d33682"),
            "object": QColor("#b58900"),
            "caret": QColor("#002b36"),
            "caret_line": QColor("#eee8d5"),
            "margin_bg": QColor("#eee8d5"),
            "margin_fg": QColor("#93a1a1"),
            "selection_bg": QColor("#93a1a1"),
            "selection_fg": QColor("#002b36"),
            "brace_bg": QColor("#85990055"),
            "brace_fg": QColor("#859900"),
            "error": QColor("#dc322f"),
            "warning": QColor("#b58900"),
            "echo": QColor("#93a1a1"),  # цвет комментария
            "autosave_on": QColor("#2aa198"),
            "autosave_off": QColor("#dc322f"),
            "status_bg": QColor("#073642"),
            "status_border": QColor("#586e75"),
        }
    },
    
    "Visual Studio Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#ffffff"),
            "fg": QColor("#000000"),
            "title_bg": QColor("#f0f0f0"),
            "title_bg_darker": QColor("#dddddd"),
            "title_fg": QColor("#000000"),
            "title_border": QColor("#cccccc"),
            "keyword": QColor("#0000ff"),
            "type": QColor("#2b91af"),
            "comment": QColor("#008000"),
            "string": QColor("#a31515"),
            "number": QColor("#09885a"),
            "operator": QColor("#000000"),
            "function": QColor("#795e26"),
            "modifier": QColor("#0000ff"),
            "directive": QColor("#008000"),
            "literal": QColor("#a31515"),
            "namespace": QColor("#267f99"),
            "special": QColor("#ff0000"),
            "object": QColor("#2b91af"),
            "caret": QColor("#000000"),
            "caret_line": QColor("#f0f0f0"),
            "margin_bg": QColor("#f0f0f0"),
            "margin_fg": QColor("#606060"),
            "selection_bg": QColor("#fff8d3"),
            "selection_fg": QColor("#000000"),
            "brace_bg": QColor("#0078d755"),
            "brace_fg": QColor("#0078d7"),
            "error": QColor("#ff0000"),
            "warning": QColor("#ff8c00"),
            "echo": QColor("#6a6a6a"),  # серее основного текста
            "autosave_on": QColor("#107c10"),
            "autosave_off": QColor("#d73a49"),
            "status_bg": QColor("#2d2d2d"),
            "status_border": QColor("#cccccc"),
        }
    },
    
    "Ayu Dark": {
    "type": "dark",
    "colors": {
        "bg": QColor("#0a0e14"),
        "fg": QColor("#b3b1ad"),
        "title_bg": QColor("#1a1f29"),
        "title_bg_darker": QColor("#0f141e"),
        "title_fg": QColor("#e6e1cf"),
        "title_border": QColor("#4c6a83"),
        "keyword": QColor("#ff8f40"),
        "type": QColor("#39bae6"),
        "comment": QColor("#626a73"),
        "string": QColor("#c2d94c"),
        "number": QColor("#d2a6ff"),
        "operator": QColor("#f29668"),
        "function": QColor("#ffb454"),
        "modifier": QColor("#4086ff"),
        "directive": QColor("#e6b450"),
        "literal": QColor("#a37acc"),
        "namespace": QColor("#39bae6"),
        "special": QColor("#f07178"),
        "object": QColor("#95e6cb"),
        "caret": QColor("#e6e1cf"),
        "caret_line": QColor("#1a1f29"),
        "margin_bg": QColor("#0d1017"),
        "margin_fg": QColor("#3e4b59"),
        "selection_bg": QColor("#273747"),
        "selection_fg": QColor("#e6e1cf"),
        "brace_bg": QColor("#ff8f4055"),
        "brace_fg": QColor("#ff8f40"),
        "error": QColor("#f07178"),
        "warning": QColor("#ffb454"),
        "echo": QColor("#8a8d93"),  # светлее фона, темнее основного текста
        "autosave_on": QColor("#c2d94c"),
        "autosave_off": QColor("#f07178"),
        "status_bg": QColor("#0d1017"),
        "status_border": QColor("#273747"),
    }
},
    
    "Ayu Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#fafafa"),
            "fg": QColor("#5c6166"),
            "title_bg": QColor("#e9e9e9"),
            "title_bg_darker": QColor("#d8d8d8"),
            "title_fg": QColor("#5c6166"),
            "title_border": QColor("#abb0b6"),
            "keyword": QColor("#fa8d3e"),
            "type": QColor("#399ee6"),
            "comment": QColor("#abb0b6"),
            "string": QColor("#86b300"),
            "number": QColor("#a37acc"),
            "operator": QColor("#ed9366"),
            "function": QColor("#f2ae49"),
            "modifier": QColor("#6a3efa"),
            "directive": QColor("#f2ae49"),
            "literal": QColor("#a37acc"),
            "namespace": QColor("#399ee6"),
            "special": QColor("#f07171"),
            "object": QColor("#4cbf99"),
            "caret": QColor("#5c6166"),
            "caret_line": QColor("#f0f0f0"),
            "margin_bg": QColor("#e9e9e9"),
            "margin_fg": QColor("#abb0b6"),
            "selection_bg": QColor("#d4d4d4"),
            "selection_fg": QColor("#5c6166"),
            "brace_bg": QColor("#fa8d3e55"),
            "brace_fg": QColor("#fa8d3e"),
            "error": QColor("#f07171"),
            "warning": QColor("#f2ae49"),
            "echo": QColor("#9a9ea3"),  # серее основного текста
            "autosave_on": QColor("#86b300"),
            "autosave_off": QColor("#f07171"),
            "status_bg": QColor("#2d3c4d"),
            "status_border": QColor("#abb0b6"),
        }
    },
    
    "Everforest Dark": {
        "type": "dark",
        "colors": {
            "bg": QColor("#2d3c4d"),
            "fg": QColor("#d3c6aa"),
            "title_bg": QColor("#3a4a5a"),
            "title_bg_darker": QColor("#2f3f4f"),
            "title_fg": QColor("#d3c6aa"),
            "title_border": QColor("#4a5a6a"),
            "keyword": QColor("#e6986c"),
            "type": QColor("#7fbbb3"),
            "comment": QColor("#859289"),
            "string": QColor("#a7c080"),
            "number": QColor("#e67e80"),
            "operator": QColor("#e6986c"),
            "function": QColor("#dbbc7f"),
            "modifier": QColor("#e6986c"),
            "directive": QColor("#e67e80"),
            "literal": QColor("#e67e80"),
            "namespace": QColor("#7fbbb3"),
            "special": QColor("#e67e80"),
            "object": QColor("#a7c080"),
            "caret": QColor("#d3c6aa"),
            "caret_line": QColor("#3a4a5a"),
            "margin_bg": QColor("#26323f"),
            "margin_fg": QColor("#859289"),
            "selection_bg": QColor("#4a5a6a"),
            "selection_fg": QColor("#d3c6aa"),
            "brace_bg": QColor("#e6986c55"),
            "brace_fg": QColor("#e6986c"),
            "error": QColor("#e67e80"),
            "warning": QColor("#e6986c"),
            "echo": QColor("#9eaf9a"),  # светлее фона
            "autosave_on": QColor("#a7c080"),
            "autosave_off": QColor("#e67e80"),
            "status_bg": QColor("#26323f"),
            "status_border": QColor("#4a5a6a"),
        }
    },
    
    "Everforest Light": {
        "type": "light",
        "colors": {
            "bg": QColor("#fef6e4"),
            "fg": QColor("#5c6a72"),
            "title_bg": QColor("#f0e8d8"),
            "title_bg_darker": QColor("#e0d8c8"),
            "title_fg": QColor("#5c6a72"),
            "title_border": QColor("#d0d8d0"),
            "keyword": QColor("#f57b5c"),
            "type": QColor("#4f9e9e"),
            "comment": QColor("#939f91"),
            "string": QColor("#8da101"),
            "number": QColor("#e65e5e"),
            "operator": QColor("#f57b5c"),
            "function": QColor("#dfb256"),
            "modifier": QColor("#f57b5c"),
            "directive": QColor("#e65e5e"),
            "literal": QColor("#e65e5e"),
            "namespace": QColor("#4f9e9e"),
            "special": QColor("#e65e5e"),
            "object": QColor("#8da101"),
            "caret": QColor("#5c6a72"),
            "caret_line": QColor("#f0e8d8"),
            "margin_bg": QColor("#e8e0d0"),
            "margin_fg": QColor("#939f91"),
            "selection_bg": QColor("#d0d8d0"),
            "selection_fg": QColor("#5c6a72"),
            "brace_bg": QColor("#f57b5c55"),
            "brace_fg": QColor("#f57b5c"),
            "error": QColor("#e65e5e"),
            "warning": QColor("#f57b5c"),
            "echo": QColor("#8c9690"),  # серее основного текста
            "autosave_on": QColor("#8da101"),
            "autosave_off": QColor("#e65e5e"),
            "status_bg": QColor("#3a4a5a"),
            "status_border": QColor("#939f91"),
        }
    },
    
    "Rosé Pine": {
        "type": "dark",
        "colors": {
            "bg": QColor("#191724"),
            "fg": QColor("#e0def4"),
            "title_bg": QColor("#26233a"),
            "title_bg_darker": QColor("#1c192d"),
            "title_fg": QColor("#e0def4"),
            "title_border": QColor("#403d52"),
            "keyword": QColor("#ebbcba"),
            "type": QColor("#9ccfd8"),
            "comment": QColor("#6e6a86"),
            "string": QColor("#f6c177"),
            "number": QColor("#c4a7e7"),
            "operator": QColor("#6e6a86"),
            "function": QColor("#ebbcba"),
            "modifier": QColor("#c4a7e7"),
            "directive": QColor("#eb6f92"),
            "literal": QColor("#f6c177"),
            "namespace": QColor("#9ccfd8"),
            "special": QColor("#eb6f92"),
            "object": QColor("#c4a7e7"),
            "caret": QColor("#e0def4"),
            "caret_line": QColor("#26233a"),
            "margin_bg": QColor("#1f1d2e"),
            "margin_fg": QColor("#6e6a86"),
            "selection_bg": QColor("#403d52"),
            "selection_fg": QColor("#e0def4"),
            "brace_bg": QColor("#ebbcba55"),
            "brace_fg": QColor("#ebbcba"),
            "error": QColor("#eb6f92"),
            "warning": QColor("#f6c177"),
            "echo": QColor("#908caa"),  # светлее фона, темнее основного текста
            "autosave_on": QColor("#9ccfd8"),
            "autosave_off": QColor("#eb6f92"),
            "status_bg": QColor("#1f1d2e"),
            "status_border": QColor("#403d52"),
        }
    },
    "Gruvbox Dark": {
    "type": "dark",
    "colors": {
        "bg": QColor("#282828"),
        "fg": QColor("#ebdbb2"),
        "title_bg": QColor("#3c3836"),
        "title_bg_darker": QColor("#2e2a29"),
        "title_fg": QColor("#fbf1c7"),
        "title_border": QColor("#504945"),
        "keyword": QColor("#fb4934"),
        "type": QColor("#8ec07c"),
        "comment": QColor("#928374"),
        "string": QColor("#b8bb26"),
        "number": QColor("#d3869b"),
        "operator": QColor("#fe8019"),
        "function": QColor("#fabd2f"),
        "modifier": QColor("#fe8019"),
        "directive": QColor("#d65d0e"),
        "literal": QColor("#d3869b"),
        "namespace": QColor("#83a598"),
        "special": QColor("#d65d0e"),
        "object": QColor("#8ec07c"),
        "caret": QColor("#fbf1c7"),
        "caret_line": QColor("#3c3836"),
        "margin_bg": QColor("#1d2021"),
        "margin_fg": QColor("#928374"),
        "selection_bg": QColor("#504945"),
        "selection_fg": QColor("#fbf1c7"),
        "brace_bg": QColor("#fb493455"),
        "brace_fg": QColor("#fb4934"),
        "error": QColor("#cc241d"),
        "warning": QColor("#d79921"),
        "echo": QColor("#a89984"),
        "autosave_on": QColor("#b8bb26"),
        "autosave_off": QColor("#cc241d"),
        "status_bg": QColor("#1d2021"),
        "status_border": QColor("#3c3836"),
    }
},
"Moonlight": {
    "type": "dark",
    "colors": {
        "bg": QColor("#1e2a3a"),
        "fg": QColor("#d9e0ee"),
        "title_bg": QColor("#2a3a4a"),
        "title_bg_darker": QColor("#22303e"),
        "title_fg": QColor("#d9e0ee"),
        "title_border": QColor("#3a4a5a"),
        "keyword": QColor("#ff8c42"),
        "type": QColor("#70c9f0"),
        "comment": QColor("#5a6e7a"),
        "string": QColor("#b3d46b"),
        "number": QColor("#ffb86c"),
        "operator": QColor("#7b8c74"),      # darker muted green, slightly darker than literal
        "function": QColor("#ff6b6b"),
        "modifier": QColor("#ff8c42"),
        "directive": QColor("#ffb86c"),
        "literal": QColor("#b3d46b"),
        "namespace": QColor("#70c9f0"),
        "special": QColor("#ff6b6b"),
        "object": QColor("#70c9f0"),
        "caret": QColor("#d9e0ee"),
        "caret_line": QColor("#2a3a4a"),
        "margin_bg": QColor("#15222e"),
        "margin_fg": QColor("#5a6e7a"),
        "selection_bg": QColor("#3a4a5a"),
        "selection_fg": QColor("#d9e0ee"),
        "brace_bg": QColor("#ff8c4255"),
        "brace_fg": QColor("#ff8c42"),
        "error": QColor("#ff6b6b"),
        "warning": QColor("#ffb86c"),
        "echo": QColor("#8a9ba8"),
        "autosave_on": QColor("#b3d46b"),
        "autosave_off": QColor("#ff6b6b"),
        "status_bg": QColor("#15222e"),
        "status_border": QColor("#2a3a4a"),
    }
},
"Emerald Forest": {
    "type": "dark",
    "colors": {
        "bg": QColor("#1e241e"),           # почти чёрный с лёгким зелёным оттенком
        "fg": QColor("#cfddcf"),           # светлый серо-зелёный (основной текст)
        "title_bg": QColor("#2a302a"),
        "title_bg_darker": QColor("#212621"),
        "title_fg": QColor("#dfecdf"),
        "title_border": QColor("#3a403a"),
        "keyword": QColor("#c6a0f6"),      # мягкий сиреневый
        "type": QColor("#7dc4e4"),         # светло-голубой (циан)
        "comment": QColor("#6a746a"),      # приглушённый серо-зелёный
        "string": QColor("#f5b88c"),       # тёплый персиковый
        "number": QColor("#e2bf7a"),       # золотистый
        "operator": QColor("#8a988a"),     # нейтральный серо-зелёный, темнее литералов
        "function": QColor("#c8d96c"),     # мягкий жёлто-зелёный
        "modifier": QColor("#b0a5f0"),     # лавандовый
        "directive": QColor("#d99e6e"),    # терракотовый
        "literal": QColor("#f5aa8c"),      # светло-коралловый (отличается от строк)
        "namespace": QColor("#6cc8b4"),    # бирюзовый
        "special": QColor("#e68c8c"),      # мягкий красный
        "object": QColor("#9acc8c"),       # приглушённая мята
        "caret": QColor("#f0f8f0"),
        "caret_line": QColor("#2a302a"),
        "margin_bg": QColor("#182018"),
        "margin_fg": QColor("#6a746a"),
        "selection_bg": QColor("#3a443a"),
        "selection_fg": QColor("#dfecdf"),
        "brace_bg": QColor("#c6a0f655"),
        "brace_fg": QColor("#c6a0f6"),
        "error": QColor("#e68c8c"),
        "warning": QColor("#e2bf7a"),
        "echo": QColor("#9aae9a"),
        "autosave_on": QColor("#c8d96c"),
        "autosave_off": QColor("#e68c8c"),
        "status_bg": QColor("#182018"),
        "status_border": QColor("#2a302a"),
    }
},
}